# Generated by Django 4.0.1 on 2022-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='postNote',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
