# Generated by Django 4.0.1 on 2022-09-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_followers_user_following1_delete_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following1',
        ),
    ]
