# Generated by Django 4.0.1 on 2022-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_user_following1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='postNote',
            field=models.TextField(),
        ),
    ]
