# Generated by Django 4.0.1 on 2022-09-27 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_post_id_alter_post_postnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
