# Generated by Django 4.0.1 on 2022-09-27 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_post_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='likerz', to=settings.AUTH_USER_MODEL),
        ),
    ]
